config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
    root to: "welcome#index"
  resources :presentations
  resources :expeditions
  resources :invitations
  resources :congresses
  resources :expositors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expositor.rb
class Expositor < ApplicationRecord
  belongs_to :user
  belongs_to :congress
end

app/controllers/expositors_controller.rb
class ExpositorsController < ApplicationController
  before_action :set_expositor, only: [:show, :edit, :update, :destroy]

  # GET /expositors
  # GET /expositors.json
  def index
    @expositors = Expositor.all
  end

  # GET /expositors/1
  # GET /expositors/1.json
  def show
  end

  # GET /expositors/new
  def new
    @expositor = Expositor.new
  end

  # GET /expositors/1/edit
  def edit
  end

  # POST /expositors
  # POST /expositors.json
  def create
    @expositor = Expositor.new(expositor_params)

    respond_to do |format|
      if @expositor.save
        format.html { redirect_to @expositor, notice: 'Expositor was successfully created.' }
        format.json { render :show, status: :created, location: @expositor }
      else
        format.html { render :new }
        format.json { render json: @expositor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expositors/1
  # PATCH/PUT /expositors/1.json
  def update
    respond_to do |format|
      if @expositor.update(expositor_params)
        format.html { redirect_to @expositor, notice: 'Expositor was successfully updated.' }
        format.json { render :show, status: :ok, location: @expositor }
      else
        format.html { render :edit }
        format.json { render json: @expositor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expositors/1
  # DELETE /expositors/1.json
  def destroy
    @expositor.destroy
    respond_to do |format|
      format.html { redirect_to expositors_url, notice: 'Expositor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expositor
      @expositor = Expositor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expositor_params
      params.require(:expositor).permit(:degree, :web, :links, :suggest, :funding, :gestor, :expedition, :state, :new_gestor, :comments, :category, :assistant, :bio, :congress, :user_id, :congress_id)
    end
end

app/helpers/expositors_helper.rb
module ExpositorsHelper
end

app/views/expositors/_form.html.erb
<%= form_with(model: expositor, local: true) do |form| %>
  <% if expositor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expositor.errors.count, "error") %> prohibited this expositor from being saved:</h2>

      <ul>
      <% expositor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree, id: :expositor_degree %>
  </div>

  <div class="field">
    <%= form.label :web %>
    <%= form.text_field :web, id: :expositor_web %>
  </div>

  <div class="field">
    <%= form.label :links %>
    <%= form.text_area :links, id: :expositor_links %>
  </div>

  <div class="field">
    <%= form.label :suggest %>
    <%= form.text_field :suggest, id: :expositor_suggest %>
  </div>

  <div class="field">
    <%= form.label :funding %>
    <%= form.text_field :funding, id: :expositor_funding %>
  </div>

  <div class="field">
    <%= form.label :gestor %>
    <%= form.text_field :gestor, id: :expositor_gestor %>
  </div>

  <div class="field">
    <%= form.label :expedition %>
    <%= form.text_field :expedition, id: :expositor_expedition %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :expositor_state %>
  </div>

  <div class="field">
    <%= form.label :new_gestor %>
    <%= form.text_field :new_gestor, id: :expositor_new_gestor %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :expositor_comments %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :expositor_category %>
  </div>

  <div class="field">
    <%= form.label :assistant %>
    <%= form.text_field :assistant, id: :expositor_assistant %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :expositor_bio %>
  </div>

  <div class="field">
    <%= form.label :congress %>
    <%= form.text_field :congress, id: :expositor_congress %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :expositor_user_id %>
  </div>

  <div class="field">
    <%= form.label :congress_id %>
    <%= form.text_field :congress_id, id: :expositor_congress_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expositors/edit.html.erb
<h1>Editing Expositor</h1>

<%= render 'form', expositor: @expositor %>

<%= link_to 'Show', @expositor %> |
<%= link_to 'Back', expositors_path %>

app/views/expositors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expositors</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th>Web</th>
      <th>Links</th>
      <th>Suggest</th>
      <th>Funding</th>
      <th>Gestor</th>
      <th>Expedition</th>
      <th>State</th>
      <th>New gestor</th>
      <th>Comments</th>
      <th>Category</th>
      <th>Assistant</th>
      <th>Bio</th>
      <th>Congress</th>
      <th>User</th>
      <th>Congress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expositors.each do |expositor| %>
      <tr>
        <td><%= expositor.degree %></td>
        <td><%= expositor.web %></td>
        <td><%= expositor.links %></td>
        <td><%= expositor.suggest %></td>
        <td><%= expositor.funding %></td>
        <td><%= expositor.gestor %></td>
        <td><%= expositor.expedition %></td>
        <td><%= expositor.state %></td>
        <td><%= expositor.new_gestor %></td>
        <td><%= expositor.comments %></td>
        <td><%= expositor.category %></td>
        <td><%= expositor.assistant %></td>
        <td><%= expositor.bio %></td>
        <td><%= expositor.congress %></td>
        <td><%= expositor.user %></td>
        <td><%= expositor.congress %></td>
        <td><%= link_to 'Show', expositor %></td>
        <td><%= link_to 'Edit', edit_expositor_path(expositor) %></td>
        <td><%= link_to 'Destroy', expositor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expositor', new_expositor_path %>

app/views/expositors/new.html.erb
<h1>New Expositor</h1>

<%= render 'form', expositor: @expositor %>

<%= link_to 'Back', expositors_path %>

app/views/expositors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @expositor.degree %>
</p>

<p>
  <strong>Web:</strong>
  <%= @expositor.web %>
</p>

<p>
  <strong>Links:</strong>
  <%= @expositor.links %>
</p>

<p>
  <strong>Suggest:</strong>
  <%= @expositor.suggest %>
</p>

<p>
  <strong>Funding:</strong>
  <%= @expositor.funding %>
</p>

<p>
  <strong>Gestor:</strong>
  <%= @expositor.gestor %>
</p>

<p>
  <strong>Expedition:</strong>
  <%= @expositor.expedition %>
</p>

<p>
  <strong>State:</strong>
  <%= @expositor.state %>
</p>

<p>
  <strong>New gestor:</strong>
  <%= @expositor.new_gestor %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @expositor.comments %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expositor.category %>
</p>

<p>
  <strong>Assistant:</strong>
  <%= @expositor.assistant %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @expositor.bio %>
</p>

<p>
  <strong>Congress:</strong>
  <%= @expositor.congress %>
</p>

<p>
  <strong>User:</strong>
  <%= @expositor.user %>
</p>

<p>
  <strong>Congress:</strong>
  <%= @expositor.congress %>
</p>

<%= link_to 'Edit', edit_expositor_path(@expositor) %> |
<%= link_to 'Back', expositors_path %>