config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
    root to: "welcome#index"
  resources :presentations
  resources :expeditions
  resources :invitations
  resources :congresses
  resources :expositors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expedition.rb
class Expedition < ApplicationRecord
  belongs_to :expositor
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
  before_action :set_expedition, only: [:show, :edit, :update, :destroy]

  # GET /expeditions
  # GET /expeditions.json
  def index
    @expeditions = Expedition.all
  end

  # GET /expeditions/1
  # GET /expeditions/1.json
  def show
  end

  # GET /expeditions/new
  def new
    @expedition = Expedition.new
  end

  # GET /expeditions/1/edit
  def edit
  end

  # POST /expeditions
  # POST /expeditions.json
  def create
    @expedition = Expedition.new(expedition_params)

    respond_to do |format|
      if @expedition.save
        format.html { redirect_to @expedition, notice: 'Expedition was successfully created.' }
        format.json { render :show, status: :created, location: @expedition }
      else
        format.html { render :new }
        format.json { render json: @expedition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expeditions/1
  # PATCH/PUT /expeditions/1.json
  def update
    respond_to do |format|
      if @expedition.update(expedition_params)
        format.html { redirect_to @expedition, notice: 'Expedition was successfully updated.' }
        format.json { render :show, status: :ok, location: @expedition }
      else
        format.html { render :edit }
        format.json { render json: @expedition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expeditions/1
  # DELETE /expeditions/1.json
  def destroy
    @expedition.destroy
    respond_to do |format|
      format.html { redirect_to expeditions_url, notice: 'Expedition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expedition
      @expedition = Expedition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expedition_params
      params.require(:expedition).permit(:year, :place, :participants, :responsable, :expositor_id)
    end
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/views/expeditions/_form.html.erb
<%= form_with(model: expedition, local: true) do |form| %>
  <% if expedition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expedition.errors.count, "error") %> prohibited this expedition from being saved:</h2>

      <ul>
      <% expedition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :expedition_year %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :expedition_place %>
  </div>

  <div class="field">
    <%= form.label :participants %>
    <%= form.text_field :participants, id: :expedition_participants %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable, id: :expedition_responsable %>
  </div>

  <div class="field">
    <%= form.label :expositor_id %>
    <%= form.text_field :expositor_id, id: :expedition_expositor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expeditions/edit.html.erb
<h1>Editing Expedition</h1>

<%= render 'form', expedition: @expedition %>

<%= link_to 'Show', @expedition %> |
<%= link_to 'Back', expeditions_path %>

app/views/expeditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expeditions</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Place</th>
      <th>Participants</th>
      <th>Responsable</th>
      <th>Expositor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expeditions.each do |expedition| %>
      <tr>
        <td><%= expedition.year %></td>
        <td><%= expedition.place %></td>
        <td><%= expedition.participants %></td>
        <td><%= expedition.responsable %></td>
        <td><%= expedition.expositor %></td>
        <td><%= link_to 'Show', expedition %></td>
        <td><%= link_to 'Edit', edit_expedition_path(expedition) %></td>
        <td><%= link_to 'Destroy', expedition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expedition', new_expedition_path %>

app/views/expeditions/new.html.erb
<h1>New Expedition</h1>

<%= render 'form', expedition: @expedition %>

<%= link_to 'Back', expeditions_path %>

app/views/expeditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @expedition.year %>
</p>

<p>
  <strong>Place:</strong>
  <%= @expedition.place %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @expedition.participants %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @expedition.responsable %>
</p>

<p>
  <strong>Expositor:</strong>
  <%= @expedition.expositor %>
</p>

<%= link_to 'Edit', edit_expedition_path(@expedition) %> |
<%= link_to 'Back', expeditions_path %>